--Duel, standby!
--Scripted by The Razgriz
local s,id=GetID()
function s.initial_effect(c)
	aux.AddSkillProcedure(c,2,false,nil,nil)
	local e1=Effect.CreateEffect(c)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_STARTUP)
	e1:SetCountLimit(1)
	e1:SetRange(0x5f)
	e1:SetLabel(0)
	e1:SetOperation(s.flipop)
	c:RegisterEffect(e1)
	local drawlesseff=Effect.GlobalEffect()
	drawlesseff:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	drawlesseff:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	drawlesseff:SetCode(EVENT_STARTUP)
	drawlesseff:SetOperation(function(e)
	Debug.SetPlayerInfo(0,Duel.GetLP(0),Duel.GetStartingHand(0)+1,Duel.GetDrawCount(0))
	Debug.SetPlayerInfo(1,Duel.GetLP(1),Duel.GetStartingHand(1)+1,Duel.GetDrawCount(1))
	e:Reset()
	end)
	Duel.RegisterEffect(drawlesseff,0)
end
function s.flipop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SKILL_FLIP,tp,id|(1<<32))
	Duel.Hint(HINT_CARD,tp,id)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_SUMMON)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_PLAYER_TARGET)
	e1:SetCondition(s.con)
	e1:SetTargetRange(1,0)
	Duel.RegisterEffect(e1,tp)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_CANNOT_ACTIVATE)
	e2:SetValue(1)
	Duel.RegisterEffect(e2,tp)
end
function s.con(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetTurnPlayer()==tp and Duel.GetTurnCount()<3
end