--サークル・オブ・ライフ
--Circle of Life
local s,id=GetID()
function s.initial_effect(c)
	--Activate
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_ACTIVATE)
	e0:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e0)
	--The turn player can send 1 Spell from their hand to the Graveyard
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(512000006,0))
	e1:SetCategory(CATEGORY_TOGRAVE)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetProperty(EFFECT_FLAG_BOTH_SIDE)
	e1:SetRange(LOCATION_SZONE)
	e1:SetCost(s.cost)
	e1:SetOperation(function(e,tp,eg,ep,ev,re,r,rp) Duel.RegisterFlagEffect(tp,id,RESET_PHASE|PHASE_END,0,1) end)
	c:RegisterEffect(e1)
	--Neither player can Set or activate Spell Cards from the hand unless they discarded a card with this card's above effect (You)
	local e2a=Effect.CreateEffect(c)
	e2a:SetType(EFFECT_TYPE_FIELD)
	e2a:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2a:SetCode(EFFECT_CANNOT_ACTIVATE)
	e2a:SetRange(LOCATION_SZONE)
	e2a:SetTargetRange(1,0)
	e2a:SetCondition(function(e) local tp=e:GetHandlerPlayer() return Duel.GetFlagEffect(tp,id)==0 end)
	e2a:SetValue(s.aclimit)
	c:RegisterEffect(e2a)
	local e2b=Effect.CreateEffect(c)
	e2b:SetType(EFFECT_TYPE_FIELD)
	e2b:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2b:SetCode(EFFECT_CANNOT_SSET)
	e2b:SetCondition(function(e) local tp=e:GetHandlerPlayer() return Duel.GetFlagEffect(tp,id)==0 end)
	e2b:SetRange(LOCATION_SZONE)
	e2b:SetTargetRange(1,0)
	e2b:SetTarget(function(e,c) return c:IsLocation(LOCATION_HAND) and c:IsSpell() end)
	c:RegisterEffect(e2b)
	--Neither player can Set or activate Spell Cards from the hand unless they discarded a card with this card's above effect (Your opponent)
	local e3a=Effect.CreateEffect(c)
	e3a:SetType(EFFECT_TYPE_FIELD)
	e3a:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3a:SetCode(EFFECT_CANNOT_ACTIVATE)
	e3a:SetRange(LOCATION_SZONE)
	e3a:SetTargetRange(0,1)
	e3a:SetCondition(function(e) local tp=e:GetHandlerPlayer() return Duel.GetFlagEffect(1-tp,id)==0 end)
	e3a:SetValue(s.aclimit)
	c:RegisterEffect(e3a)
	local e3b=Effect.CreateEffect(c)
	e3b:SetType(EFFECT_TYPE_FIELD)
	e3b:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3b:SetCode(EFFECT_CANNOT_SSET)
	e3b:SetCondition(function(e) local tp=e:GetHandlerPlayer() return Duel.GetFlagEffect(1-tp,id)==0 end)
	e3b:SetRange(LOCATION_SZONE)
	e3b:SetTargetRange(0,1)
	e3b:SetTarget(function(e,c) return c:IsLocation(LOCATION_HAND) and c:IsSpell() end)
	c:RegisterEffect(e3b)
end
function s.cost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(aux.AND(Card.IsSpell,Card.IsAbleToGraveAsCost),tp,LOCATION_HAND,0,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local g=Duel.SelectMatchingCard(tp,aux.AND(Card.IsSpell,Card.IsAbleToGraveAsCost),tp,LOCATION_HAND,0,1,1,nil)
	Duel.SendtoGrave(g,REASON_COST)
end
function s.aclimit(e,re,tp)
	if not re or not re:IsHasType(EFFECT_TYPE_ACTIVATE) or not re:IsSpellEffect() then return false end
	local c=re:GetHandler()
	return c:IsLocation(LOCATION_HAND) and c:IsSpell()
end

