--DDD超死偉王ホワイテスト・ヘル・アーマゲドン (Anime)
--D/D/D Super Doom King Bright Armageddon (Anime)
--fixed by Larry126 and MLD
local s,id,alias=GetID()
function s.initial_effect(c)
	alias=c:GetOriginalCodeRule()
	c:EnableReviveLimit()
	--Synchro Summon procedure: 1 "D/D" Tuner + 1 or more non-Tuner "D/D" monsters
	Synchro.AddProcedure(c,aux.FilterBoolFunctionEx(Card.IsSetCard,SET_DD),1,1,Synchro.NonTunerEx(Card.IsSetCard,SET_DD),1,99)
	--Pendulum procedure
	Pendulum.AddProcedure(c,false)
	--Synchro Monsters you control cannot be destroyed by battle or card effects
	local e1a=Effect.CreateEffect(c)
	e1a:SetType(EFFECT_TYPE_FIELD)
	e1a:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e1a:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
	e1a:SetRange(LOCATION_PZONE)
	e1a:SetTargetRange(LOCATION_MZONE,0)
	e1a:SetTarget(aux.TargetBoolFunction(Card.IsType,TYPE_SYNCHRO))
	e1a:SetValue(1)
	c:RegisterEffect(e1a)
	local e1b=e1a:Clone()
	e1b:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	c:RegisterEffect(e1b)
	--Your opponent cannot target Synchro Monsters you control with card effects
	local e2=e1a:Clone()
	e2:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e2:SetValue(aux.tgoval)
	c:RegisterEffect(e2)
	--The effects of monsters you control cannot be negated 
	local e3a=Effect.CreateEffect(c)
	e3a:SetType(EFFECT_TYPE_FIELD)
	e3a:SetCode(EFFECT_CANNOT_DISABLE)
	e3a:SetRange(LOCATION_MZONE)
	e3a:SetTargetRange(LOCATION_MZONE,0)
	c:RegisterEffect(e3a)
	local e3b=e3a:Clone()
	e3b:SetCode(EFFECT_CANNOT_DISEFFECT)
	e3b:SetValue(1)
	c:RegisterEffect(e3b)
	--If a monster(s) is Normal or Special Summoned: You can activate this effect; your opponent chooses 1 Pendulum Monster they control, and all other monsters they control have their effects negated, until the next time a monster(s) is Normal or Special Summoned
	local e4a=Effect.CreateEffect(c)
	e4a:SetDescription(aux.Stringid(alias,1))
	e4a:SetCategory(CATEGORY_DISABLE)
	e4a:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e4a:SetProperty(EFFECT_FLAG_DELAY)
	e4a:SetCode(EVENT_SUMMON_SUCCESS)
	e4a:SetRange(LOCATION_MZONE)
	e4a:SetTarget(s.distg)
	e4a:SetOperation(s.disop)
	c:RegisterEffect(e4a)
	local e4b=e4a:Clone()
	e4b:SetCode(EVENT_SPSUMMON_SUCCESS)
	c:RegisterEffect(e4b)
end
s.listed_series={SET_DD}
function s.disfilter(c,tp)
	return c:IsFaceup() and c:IsType(TYPE_PENDULUM)
		and Duel.IsExistingMatchingCard(Card.IsNegatableMonster,tp,0,LOCATION_MZONE,1,c)
end
function s.distg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return not eg:IsContains(e:GetHandler())
		and Duel.IsExistingMatchingCard(s.disfilter,tp,0,LOCATION_MZONE,1,nil,tp) end
	local g=Duel.GetMatchingGroup(Card.IsNegatableMonster,tp,0,LOCATION_MZONE,pc)
	Duel.SetOperationInfo(0,CATEGORY_DISABLE,g,#g-1,0,0)
end
function s.disop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,1-tp,aux.Stringid(alias,2))
	local pg=Duel.SelectMatchingCard(1-tp,s.disfilter,tp,0,LOCATION_MZONE,1,1,nil,tp)
	local pc=pg:GetFirst()
	if not pc then return end
	Duel.HintSelection(pg)
	local c=e:GetHandler()
	local flag=(id+c:GetFieldID()+e:GetFieldID())*2
	local g=Duel.GetMatchingGroup(Card.IsNegatableMonster,tp,0,LOCATION_MZONE,pc)
	g:ForEach(function(tc)
		tc:RegisterFlagEffect(flag,RESET_EVENT|RESETS_STANDARD,0,1)
		--The chosen monster's effects are negated
		Duel.NegateRelatedChain(tc,RESET_TURN_SET)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetLabel(flag)
		e1:SetCondition(s.discon)
		e1:SetReset(RESET_EVENT|RESETS_STANDARD)
		tc:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetLabelObject(e1)
		e2:SetValue(RESET_TURN_SET)
		tc:RegisterEffect(e2)
		--Reset the negation when another monster is Normal or Special Summoned
		local e3=Effect.CreateEffect(c)
		e3:SetDescription(aux.Stringid(45014450,2))
		e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e3:SetCode(EVENT_SUMMON_SUCCESS)
		e3:SetLabel(flag)
		e3:SetLabelObject(e2)
		e3:SetRange(LOCATION_MZONE)
		e3:SetOperation(s.resetop)
		e3:SetReset(RESET_EVENT|RESETS_STANDARD)
		Duel.RegisterEffect(e3,tp)
		local e4=e3:Clone()
		e4:SetCode(EVENT_SPSUMMON_SUCCESS)
		e4:SetLabelObject(e3)
		Duel.RegisterEffect(e4,tp)
		e3:SetLabelObject(e4)
	end)
end
function s.resetfilter(c,flag)
	return c:GetFlagEffect(flag)>0
end
function s.resetop(e,tp,eg,ep,ev,re,r,rp)
	local g=Duel.GetMatchingGroup(s.resetfilter,tp,LOCATION_MZONE,LOCATION_MZONE,nil,e:GetLabel())
	g:ForEach(function(tc)
		tc:ResetFlagEffect(e:GetLabel())
	end)
	e:Reset()
	e:GetLabelObject():Reset()
end
function s.discon(e)
	if e:GetHandler():GetFlagEffect(e:GetLabel())>0 then return true
	else e:Reset() return false end
end
