name: Pull request difference archive
on: [pull_request]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy modified files
      id: copy
      run: |
        mkdir -p diff
        cp $(git diff --name-only --diff-filter=d origin/${{ github.base_ref }}) diff
    - name: Upload difference zip
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('diff__{0}__{1}', github.head_ref, github.sha) }}
        path: diff
